#!/bin/bash

# Shell script to demonstrate how to customize and run the financial planning tools
# This script shows how to modify the Python files for custom business data

echo "==============================================="
echo "Customizing Financial Planning Tools Demo"
echo "==============================================="
echo
echo "This demo shows how to customize the tools for specific business needs."
echo

# Change to the src directory
cd /common/active/sblo/Dev/Manager/DummyMusicCompany/src

echo "Available Python tools in the src directory:"
echo "-------------------------------------------"
ls *.py | sort
echo

echo "To customize a tool for your specific business:"
echo "1. Copy the Python file to a new name"
echo "2. Modify the create_sample_plan() function with your business data"
echo "3. Run the customized script"
echo

echo "Example command to run a tool:"
echo "python yt4_taloussuunnitelma_lapua.py"
echo

echo "Example command to run with custom parameters (if supported):"
echo "python -c \"exec(open('yt4_taloussuunnitelma_lapua.py').read()); custom_plan = create_sample_plan(); custom_plan.company_name = 'My Business'; print('Custom plan for:', custom_plan.company_name)\""
echo

echo "JSON output files are generated by each tool:"
echo "------------------------------------------"
ls *.json 2>/dev/null || echo "No JSON files in current directory yet"
echo

echo "==============================================="
echo "Customization demo completed!"
echo "Refer to the Python source files for implementation details."
echo "==============================================="